// AUTO-GENERATED by scripts/snapshot-catalog.ts. Do not edit by hand.
// Run `pnpm snapshot` to regenerate from Orthogonal /v1/details.
// Source: scripts/curated-endpoints.json + live /v1/details at snapshot time.

export interface CatalogParam {
  name: string;
  type: string;
  required: boolean;
  description: string;
}

export interface CatalogEndpoint {
  slug: string;
  api: string;
  path: string;
  method: "GET" | "POST" | "PUT" | "DELETE" | "PATCH";
  description: string;
  priceCents: number;
  pathParams: CatalogParam[];
  queryParams: CatalogParam[];
  bodyParams: CatalogParam[];
  verified: boolean;
}

export const catalog = [
  {
    "slug": "apollo_organizations_enrich",
    "api": "apollo",
    "path": "/api/v1/organizations/enrich",
    "method": "GET",
    "description": "Enrich a company by domain. Returns industry, revenue, employee count, funding, locations, and more.",
    "priceCents": 1,
    "pathParams": [],
    "queryParams": [
      {
        "name": "domain",
        "type": "string",
        "required": true,
        "description": "Company domain to enrich (e.g., apollo.io)"
      }
    ],
    "bodyParams": [],
    "verified": true
  },
  {
    "slug": "apollo_people_match",
    "api": "apollo",
    "path": "/api/v1/people/match",
    "method": "POST",
    "description": "Enrich a person by email, LinkedIn URL, name+company, or other identifiers. Returns contact details, job info, and social profiles.",
    "priceCents": 1,
    "pathParams": [],
    "queryParams": [],
    "bodyParams": [
      {
        "name": "email",
        "type": "string",
        "required": false,
        "description": "Email address to match"
      },
      {
        "name": "linkedin_url",
        "type": "string",
        "required": false,
        "description": "LinkedIn profile URL"
      },
      {
        "name": "first_name",
        "type": "string",
        "required": false,
        "description": "First name (use with last_name and organization)"
      },
      {
        "name": "last_name",
        "type": "string",
        "required": false,
        "description": "Last name"
      },
      {
        "name": "organization_name",
        "type": "string",
        "required": false,
        "description": "Company name"
      },
      {
        "name": "domain",
        "type": "string",
        "required": false,
        "description": "Company domain"
      },
      {
        "name": "reveal_personal_emails",
        "type": "boolean",
        "required": false,
        "description": "Include personal emails in response"
      },
      {
        "name": "reveal_phone_number",
        "type": "boolean",
        "required": false,
        "description": "Include phone numbers in response"
      }
    ],
    "verified": true
  },
  {
    "slug": "apollo_mixed_people_search",
    "api": "apollo",
    "path": "/api/v1/mixed_people/api_search",
    "method": "POST",
    "description": "Search Apollo database for people matching filters. Returns up to 100 results per page. Does not include emails/phones - use enrichment endpoints for that.",
    "priceCents": 0,
    "pathParams": [],
    "queryParams": [],
    "bodyParams": [
      {
        "name": "person_titles",
        "type": "array",
        "required": false,
        "description": "Job titles to filter by"
      },
      {
        "name": "person_seniorities",
        "type": "array",
        "required": false,
        "description": "Seniority levels (owner, founder, c_suite, partner, vp, head, director, manager, senior, entry)"
      },
      {
        "name": "organization_locations",
        "type": "array",
        "required": false,
        "description": "Company HQ locations"
      },
      {
        "name": "organization_num_employees_ranges",
        "type": "array",
        "required": false,
        "description": "Employee count ranges"
      },
      {
        "name": "person_locations",
        "type": "array",
        "required": false,
        "description": "Person locations"
      },
      {
        "name": "q_keywords",
        "type": "string",
        "required": false,
        "description": "Keywords to search"
      },
      {
        "name": "page",
        "type": "integer",
        "required": false,
        "description": "Page number (1-500)"
      },
      {
        "name": "per_page",
        "type": "integer",
        "required": false,
        "description": "Results per page (max 100)"
      }
    ],
    "verified": true
  },
  {
    "slug": "hunter_domain_search",
    "api": "hunter",
    "path": "/v2/domain-search",
    "method": "GET",
    "description": "Find all email addresses for a domain. Returns emails with sources, confidence scores, and verification status.",
    "priceCents": 1,
    "pathParams": [],
    "queryParams": [
      {
        "name": "domain",
        "type": "string",
        "required": true,
        "description": "Domain to search (e.g. stripe.com)"
      },
      {
        "name": "limit",
        "type": "integer",
        "required": false,
        "description": "Max emails to return (default 10)"
      },
      {
        "name": "offset",
        "type": "integer",
        "required": false,
        "description": "Skip N emails"
      },
      {
        "name": "type",
        "type": "string",
        "required": false,
        "description": "Filter: personal or generic"
      },
      {
        "name": "seniority",
        "type": "string",
        "required": false,
        "description": "Filter: junior, senior, or executive"
      },
      {
        "name": "department",
        "type": "string",
        "required": false,
        "description": "Filter by department (sales, marketing, etc)"
      }
    ],
    "bodyParams": [],
    "verified": false
  },
  {
    "slug": "hunter_email_finder",
    "api": "hunter",
    "path": "/v2/email-finder",
    "method": "GET",
    "description": "Find the most likely email address for a person given their name and company domain.",
    "priceCents": 1,
    "pathParams": [],
    "queryParams": [
      {
        "name": "domain",
        "type": "string",
        "required": false,
        "description": "Company domain (e.g. reddit.com)"
      },
      {
        "name": "company",
        "type": "string",
        "required": false,
        "description": "Company name (domain preferred)"
      },
      {
        "name": "first_name",
        "type": "string",
        "required": false,
        "description": "Person first name"
      },
      {
        "name": "last_name",
        "type": "string",
        "required": false,
        "description": "Person last name"
      },
      {
        "name": "full_name",
        "type": "string",
        "required": false,
        "description": "Full name (if first/last not available)"
      },
      {
        "name": "linkedin_handle",
        "type": "string",
        "required": false,
        "description": "LinkedIn profile handle"
      }
    ],
    "bodyParams": [],
    "verified": false
  },
  {
    "slug": "hunter_companies_find",
    "api": "hunter",
    "path": "/v2/companies/find",
    "method": "GET",
    "description": "Get detailed company information from a domain - industry, description, location, size, tech stack, funding.",
    "priceCents": 1,
    "pathParams": [],
    "queryParams": [
      {
        "name": "domain",
        "type": "string",
        "required": true,
        "description": "Company domain to enrich (e.g. hunter.io)"
      }
    ],
    "bodyParams": [],
    "verified": false
  },
  {
    "slug": "tomba_email_verifier",
    "api": "tomba",
    "path": "/v1/email-verifier",
    "method": "GET",
    "description": "Verify the deliverability of an email address.",
    "priceCents": 1,
    "pathParams": [],
    "queryParams": [
      {
        "name": "email",
        "type": "string",
        "required": true,
        "description": "The email address to verify"
      }
    ],
    "bodyParams": [],
    "verified": true
  },
  {
    "slug": "linkup_search",
    "api": "linkup",
    "path": "/search",
    "method": "POST",
    "description": "The /search endpoint allows you to retrieve web content.",
    "priceCents": 1,
    "pathParams": [],
    "queryParams": [],
    "bodyParams": [
      {
        "name": "q",
        "type": "string",
        "required": true,
        "description": "The natural language question for which you want to retrieve context."
      },
      {
        "name": "depth",
        "type": "string",
        "required": true,
        "description": "Defines the precision of the search. standard returns results faster; deep takes longer but yields more comprehensive results."
      },
      {
        "name": "outputType",
        "type": "string",
        "required": true,
        "description": "The type of output you want to get. Use structured for a custom-formatted response defined by structuredOutputSchema."
      },
      {
        "name": "structuredOutputSchema",
        "type": "object",
        "required": false,
        "description": "Required only when outputType is structured. Provide a JSON schema (as a string) representing the desired response format. The root must be of type object."
      },
      {
        "name": "includeSources",
        "type": "boolean",
        "required": false,
        "description": "Relevant only when outputType is structured. Defines whether the response should include sources. Please note that it modifies the schema of the response, see below"
      },
      {
        "name": "includeImages",
        "type": "boolean",
        "required": false,
        "description": "Defines whether the API should include images in its results."
      },
      {
        "name": "fromDate",
        "type": "string",
        "required": false,
        "description": "The date from which the search results should be considered, in ISO 8601 format (YYYY-MM-DD). It must be before toDate, if provided, and later than 1970-01-01."
      },
      {
        "name": "toDate",
        "type": "string",
        "required": false,
        "description": "The date until which the search results should be considered, in ISO 8601 format (YYYY-MM-DD). It must be later than fromDate, if provided, or than 1970-01-01."
      },
      {
        "name": "includeDomains",
        "type": "string[]",
        "required": false,
        "description": "The domains you want to search on. By default, don't restrict the search. You can provide up to 100 domains."
      },
      {
        "name": "excludeDomains",
        "type": "string[]",
        "required": false,
        "description": "The domains you want to exclude of the search. By default, don't restrict the search."
      },
      {
        "name": "includeInlineCitations",
        "type": "boolean",
        "required": false,
        "description": "Relevant only when outputType is sourcedAnswer. Defines whether the answer should include inline citations."
      },
      {
        "name": "maxResults",
        "type": "number",
        "required": false,
        "description": "The maximum number of results to return."
      }
    ],
    "verified": true
  },
  {
    "slug": "olostep_scrapes",
    "api": "olostep",
    "path": "/v1/scrapes",
    "method": "POST",
    "description": "Initiate a web page scrape",
    "priceCents": 1,
    "pathParams": [],
    "queryParams": [],
    "bodyParams": [
      {
        "name": "url_to_scrape",
        "type": "string",
        "required": true,
        "description": "The URL to start scraping from."
      },
      {
        "name": "wait_before_scraping",
        "type": "integer",
        "required": false,
        "description": "Time to wait in milliseconds before starting the scraping."
      },
      {
        "name": "formats",
        "type": "string[]",
        "required": false,
        "description": "Formats in which you want the content."
      },
      {
        "name": "remove_css_selectors",
        "type": "string",
        "required": false,
        "description": "Option to remove certain CSS selectors from the content. Optionally, you can also pass a JSON stringified array of specific selectors you want to remove. The CSS selectors removed when this option is set to default are ['nav','footer','script','style','noscript','svg',[role=alert],[role=banner],[role=dialog],[role=alertdialog],[role=region][aria-label*=skip i],[aria-modal=true]] Available options: `default`, `none`, `array`"
      },
      {
        "name": "actions",
        "type": "object[]",
        "required": false,
        "description": "Actions to perform on the page before getting the content."
      },
      {
        "name": "country",
        "type": "string",
        "required": false,
        "description": "Residential country to load the request from. Supported values are: * US (United States) * CA (Canada) * IT (Italy) * IN (India) * GB (England) * JP (Japan) * MX (Mexico) * AU (Australia) * ID (Indonesia) * UA (UAE) * RU (Russia) * RANDOM Some operations, like scraping Google Search and Google News, support all countries."
      },
      {
        "name": "transformer",
        "type": "string",
        "required": false,
        "description": "Specify the HTML transformer to use, if any. Postlight's Mercury Parser library is used to remove ads and other unwanted content from the scraped content. Available options: `postlight`, `none`"
      },
      {
        "name": "remove_images",
        "type": "boolean",
        "required": false,
        "description": "Option to remove images from the scraped content. Defaults to false."
      },
      {
        "name": "remove_class_names",
        "type": "string[]",
        "required": false,
        "description": "List of class names to remove from the content."
      },
      {
        "name": "parser",
        "type": "object",
        "required": false,
        "description": "When defining json as a format, you can use this parameter to specify the parser to use. Parsers are useful to extract structured content from web pages. Olostep has a few parsers built in for most common web pages, and you can also create your own parsers."
      },
      {
        "name": "llm_extract",
        "type": "object",
        "required": false,
        "description": ""
      },
      {
        "name": "links_on_page",
        "type": "object",
        "required": false,
        "description": "With this option, you can get all the links present on the page you scrape."
      },
      {
        "name": "screen_size",
        "type": "object",
        "required": false,
        "description": "Configuration for screen size. Preset dimensions are available through screen_type: desktop (1920x1080), mobile (414x896), or default (768x1024)."
      },
      {
        "name": "metadata",
        "type": "object",
        "required": false,
        "description": "User-defined metadata. Not supported yet"
      }
    ],
    "verified": true
  }
] as const satisfies readonly CatalogEndpoint[];

export type CatalogSlug = (typeof catalog)[number]["slug"];
