import dotenv from "dotenv";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

dotenv.config({ path: ".env.local" });

const BASE = "https://api.orthogonal.com";
const KEY = process.env.ORTHOGONAL_API_KEY;
if (!KEY) {
  console.error("ORTHOGONAL_API_KEY missing in .env.local");
  process.exit(1);
}

const headers = {
  Authorization: `Bearer ${KEY}`,
  "Content-Type": "application/json",
};

const CURATED_FILE = "scripts/curated-endpoints.json";
const OUTPUT_FILE = "lib/orthogonal/catalog.generated.ts";

interface CuratedEntry {
  api: string;
  path: string;
  slug: string;
  description?: string;
}

interface CatalogParam {
  name: string;
  type: string;
  required: boolean;
  description: string;
}

interface CatalogEndpoint {
  slug: string;
  api: string;
  path: string;
  method: "GET" | "POST" | "PUT" | "DELETE" | "PATCH";
  description: string;
  priceCents: number;
  pathParams: CatalogParam[];
  queryParams: CatalogParam[];
  bodyParams: CatalogParam[];
  verified: boolean;
}

async function fetchJson(method: string, path: string, body?: unknown): Promise<unknown> {
  const res = await fetch(`${BASE}${path}`, {
    method,
    headers,
    body: body ? JSON.stringify(body) : undefined,
  });
  if (!res.ok) {
    const text = await res.text().catch(() => "");
    throw new Error(`${method} ${path} failed: ${res.status} ${text.slice(0, 200)}`);
  }
  return res.json();
}

function loadCurated(): CuratedEntry[] | null {
  if (!existsSync(CURATED_FILE)) return null;
  const raw = readFileSync(CURATED_FILE, "utf-8");
  const parsed = JSON.parse(raw) as unknown;
  if (!Array.isArray(parsed)) {
    throw new Error(`${CURATED_FILE} must be a JSON array of {api, path, slug} objects.`);
  }
  return parsed as CuratedEntry[];
}

function normalizeParams(raw: unknown): CatalogParam[] {
  if (!Array.isArray(raw)) return [];
  return raw.map((p) => {
    const r = p as Record<string, unknown>;
    return {
      name: String(r.name ?? ""),
      type: String(r.type ?? "string"),
      required: Boolean(r.required),
      description: String(r.description ?? ""),
    };
  });
}

async function getDetails(api: string, path: string): Promise<{
  description: string;
  priceCents: number;
  method: CatalogEndpoint["method"];
  pathParams: CatalogParam[];
  queryParams: CatalogParam[];
  bodyParams: CatalogParam[];
  verified: boolean;
}> {
  const data = (await fetchJson("POST", "/v1/details", { api, path })) as Record<string, unknown>;
  const ep = (data.endpoint ?? {}) as Record<string, unknown>;
  const apiInfo = (data.api ?? {}) as Record<string, unknown>;
  const price = typeof ep.price === "number" ? ep.price : 0;
  const method = String(ep.method ?? "GET").toUpperCase() as CatalogEndpoint["method"];
  return {
    description: String(ep.description ?? ""),
    priceCents: Math.round(price * 100),
    method,
    pathParams: normalizeParams(ep.pathParams),
    queryParams: normalizeParams(ep.queryParams),
    bodyParams: normalizeParams(ep.bodyParams),
    verified: Boolean(apiInfo.verified),
  };
}

function formatTs(catalog: CatalogEndpoint[]): string {
  const banner =
    `// AUTO-GENERATED by scripts/snapshot-catalog.ts. Do not edit by hand.\n` +
    `// Run \`pnpm snapshot\` to regenerate from Orthogonal /v1/details.\n` +
    `// Source: scripts/curated-endpoints.json + live /v1/details at snapshot time.\n\n`;
  const types =
    `export interface CatalogParam {\n` +
    `  name: string;\n` +
    `  type: string;\n` +
    `  required: boolean;\n` +
    `  description: string;\n` +
    `}\n\n` +
    `export interface CatalogEndpoint {\n` +
    `  slug: string;\n` +
    `  api: string;\n` +
    `  path: string;\n` +
    `  method: "GET" | "POST" | "PUT" | "DELETE" | "PATCH";\n` +
    `  description: string;\n` +
    `  priceCents: number;\n` +
    `  pathParams: CatalogParam[];\n` +
    `  queryParams: CatalogParam[];\n` +
    `  bodyParams: CatalogParam[];\n` +
    `  verified: boolean;\n` +
    `}\n\n`;
  const body =
    `export const catalog = ${JSON.stringify(catalog, null, 2)} as const satisfies readonly CatalogEndpoint[];\n\n` +
    `export type CatalogSlug = (typeof catalog)[number]["slug"];\n`;
  return banner + types + body;
}

async function main() {
  const curated = loadCurated();
  if (curated === null) {
    console.warn(`No ${CURATED_FILE} yet. Skipping snapshot (no-op exit).`);
    console.warn(`Define the curated set first (Phase 2 step 7 of SPEC.md section 13), then re-run \`pnpm snapshot\`.`);
    process.exit(0);
  }

  if (curated.length === 0) {
    console.error(`${CURATED_FILE} is empty. Add 8 to 12 endpoint entries.`);
    process.exit(1);
  }

  console.log(`Snapshotting ${curated.length} curated endpoint(s)...\n`);

  const out: CatalogEndpoint[] = [];
  for (const entry of curated) {
    try {
      const d = await getDetails(entry.api, entry.path);
      out.push({
        slug: entry.slug,
        api: entry.api,
        path: entry.path,
        method: d.method,
        description: entry.description ?? d.description,
        priceCents: d.priceCents,
        pathParams: d.pathParams,
        queryParams: d.queryParams,
        bodyParams: d.bodyParams,
        verified: d.verified,
      });
      console.log(`  [OK]   ${entry.slug.padEnd(30)} ${entry.api} ${entry.path}  (${d.priceCents}c, ${d.method})`);
    } catch (err) {
      console.error(`  [FAIL] ${entry.slug}: ${err instanceof Error ? err.message : err}`);
      process.exit(1);
    }
  }

  mkdirSync("lib/orthogonal", { recursive: true });
  const outPath = resolve(OUTPUT_FILE);
  writeFileSync(outPath, formatTs(out));
  console.log(`\nWrote ${out.length} endpoint(s) to ${OUTPUT_FILE}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(2);
});
